### ISSUE TITLE
autoload constant AWS error

### ISSUE THREAD

**Issue by kahea** [edurange/edurange#2]
I'm getting the foloowing error when i run 'rails c' or similar commands.

/home/higgz/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:495:in `load_missing_constant': Unable to autoload constant AWS, expected /home/higgz/Dropbox/dev/edu/edurange/edurange/app/models/concerns/aws.rb to define it (LoadError)
        from /home/higgz/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in `const_missing'
        from /home/higgz/Dropbox/dev/edu/edurange/edurange/config/initializers/01_aws.rb:1:in `<top (required)>'
        from /home/higgz/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
        from /home/higgz/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
        from /home/higgz/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/higgz/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
        from /home/higgz/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:652:in `block in load_config_initializer'
        from /home/higgz/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:166:in `instrument'
        from /home/higgz/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:651:in `load_config_initializer'
        from /home/higgz/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
        from /home/higgz/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in `each'
        from /home/higgz/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in `block in <class:Engine>'
        from /home/higgz/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/higgz/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
        from /home/higgz/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
        from /usr/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /usr/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
        from /usr/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
        from /home/higgz/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `each'
        from /home/higgz/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `tsort_each_child'
        from /usr/lib/ruby/2.2.0/tsort.rb:413:in `call'
        from /usr/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /usr/lib/ruby/2.2.0/tsort.rb:345:in `each'
        from /usr/lib/ruby/2.2.0/tsort.rb:345:in `call'
        from /usr/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
        from /usr/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
        from /usr/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
        from /home/higgz/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/higgz/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
        from /home/higgz/Dropbox/dev/edu/edurange/edurange/config/environment.rb:5:in `<top (required)>'
        from /home/higgz/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
        from /home/higgz/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/higgz/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/higgz/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
        from /home/higgz/.gem/ruby/2.2.0/gems/spring-1.3.2/lib/spring/application.rb:92:in `preload'
        from /home/higgz/.gem/ruby/2.2.0/gems/spring-1.3.2/lib/spring/application.rb:143:in `serve'
        from /home/higgz/.gem/ruby/2.2.0/gems/spring-1.3.2/lib/spring/application.rb:131:in `block in run'
        from /home/higgz/.gem/ruby/2.2.0/gems/spring-1.3.2/lib/spring/application.rb:125:in `loop'
        from /home/higgz/.gem/ruby/2.2.0/gems/spring-1.3.2/lib/spring/application.rb:125:in `run'
        from /home/higgz/.gem/ruby/2.2.0/gems/spring-1.3.2/lib/spring/application/boot.rb:18:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'

**Comment by kahea** [comment]
This is fixed now. The gem 'aws-sdk' needed to be locked at a version below 2.0.
